### PR TITLE
Fix issues #18, #27, #28

### PR DESCRIPTION
**Pull request by sekrett**
Hello!

Please review my patches and release a new version. If required I signed the agreement to become a Chef contributor.

Finally this cookbook is good to be used in production. Now it uses completely different approach and new file format. Just to be sure it works correct I did some manual tests:
1. No option file, Chef sets options then I rewrite with make config.
2. No option file. I run make config, change two options, then Chef changes two options.

Every time I got a great result which is self explanatory:

<pre># diff options.chef options.freebsd
1c1
< # This file is auto-generated by Chef.

---
> # This file is auto-generated by 'make config'.</pre>

Still this cookbook needs support for radio options, maybe in a next version. But now it really works with boolean ones which are the majority.

### CODE REVIEW

**Comment by sekrett** [comment]
Hello! I have added port_path back from Chef source, which is much better, so there is no need to require category name from user, sorry for that.

**Comment by sekrett** [comment]
Will you accept this? I don't know how to fix foodcritic error, a shell run is required there. It is not my fault Chef fails on second port install, I did a working wrapper which works. Answer something please. Still there is much work to do for FreeBSD, but if you don't need it, I will write my own private plugin and use it and be happy.

**Comment by sekrett** [comment]
I found the reason why a port is trying to install again when it is already installed: https://github.com/chef/chef/pull/4890
It will be fixed in Chef core later, @lamont-granquist told so.

Right now as a workaround I do monkey patch for Chef, I put port.rb and pkgng.rb in `libraries` folder to make it work. Maybe a note in readme about this workaround would be nice.

I will remove freebsd_port wrapper from this PR and rebase.

**Comment by martinisoft** [comment]
Hiya @sekrett it looks like you'll need to do some updates to this PR to get it back to merge status. If you can, please avoid bumping the version directly in a PR just in case we bunch multiple changes in succession, it helps with merge conflicts down the road. Also, in order to to this project you'll need to agree to the new Developer Certificate of Origin by signing each of your commits per: https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco

**Comment by sekrett** [comment]
@martinisoft Sorry for bumping version, I needed that because I use this forked version of cookbook in my other cookbooks right now. I need some time to refresh this PR. Something else might be wrong, I don't remember now. I will tell you when this PR is ready.

**Comment by sekrett** [comment]
@martinisoft Now it is ok, I checked again, upgraded from upstream, rebased and signed. Should be ok for merging. Please tell me if it is good. Current version 1.0 of cookbook is completely useless since options format is changed and old format is not being parsed in FreeBSD, paths are also wrong. I was using my fork for a year or so to install different ports with modified options, so it is well tested in production.
Not sure about `freebsd_port` provider, it just works but it should be integrated in Chef core somehow, don't know how to do it. You may think it is a temporary workaround.

**Comment by tas50** [comment]
@sekrett I appreciate you've taken the time to put this together, but I'm a bit confused on what the end goal is. It  sounds like port_options need to be updated for the new format and that makes sense here, but the ports provider already exists within the chef-client itself. Our goal is to make sure we support package installation within core chef and we've worked to move code like this out of these cookbooks. Can you take a look at https://github.com/chef/chef/blob/master/lib/chef/provider/package/freebsd/port.rb and open an issue with chef/chef regarding anything that's missing.

**Comment by sekrett** [comment]
Yes, you are completely right, installation should not be performed by a cookbook but by core Chef.  So if you want to fix this the right way then port_options should also be removed from this cookbook and moved to Chef core. I added installation feature here because it take ages for new Chef version to be released and I need to install packages correctly today. I told already this a workaround. The end goal is the ability to install a package (port) with custom options.

**Review by xorima — APPROVED** [review]

**Review by xorima — APPROVED** [review]

**Comment by Stromweld** [comment]
Due to age and possibly not being relevant anymore I'm closing this PR. If this is still needed please feel free to reopen, rebase, and resolve any conflicts so this can be merged.

**Pull request closed without merging**
